### PR TITLE
Adds imagery for Pavo Linnaeus

### PR DESCRIPTION
**Pull request by cauldnz**
- Add imagery for Pavo linnaeus (the common peacock). This specific image chosen for most excellent display of plumage

### CODE REVIEW

**Comment by nanmu42** [comment]
Hi, thanks for your contribution. The peacock is great!

> Specific image chose for most excellent display of plumage

I wonder what does this commit mean? It seems that a imagine is missed on purpose. Would you provide a screenshot or explanation?
Thank you!

**Comment by cauldnz** [comment]
> I wonder what does this commit mean?

This is just me being 'funny'. There were a number of images for the peacock. This one has his tail up showing his 'plumage' very well. He will make an excellent employee in FAANG.

**Review by nanmu42 — APPROVED** [review]
Thanks for your contribution. I will do some final touch.

**Comment by nanmu42** [comment]
image

**Pull request merged**
